### ISSUE TITLE
"RGB Curve" Node doesn't save or apply corretly

### ISSUE THREAD

**Issue by m0dest-Wyp** [Trantor2098/hot_node#3]
首先谢谢老哥的插件，真的好用，我把我近百个Preset都存档了~比心~

老哥 应该是国人吧，我直接双语写了。

1."RGB Curve" Node doesn't save or apply corretly。

2.无论老版本0.3 还是0.4 刷新时都会有 这样的报错

Python: Traceback (most recent call last):
  File "C:\Users\m0dest\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\hot_node\operators.py", line 733, in execute
    sync_data(context)
  File "C:\Users\m0dest\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\hot_node\operators.py", line 33, in sync_data
    select_pack(context, properties.pack_selected)
  File "C:\Users\m0dest\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\hot_node\operators.py", line 54, in select_pack
    type = tree_types[name]
           ~~~~~~~~~~^^^^^^
KeyError: 'Preset'

**Comment by Trantor2098** [comment]
感谢反馈，加急修复中T T，修复好了会立即推送0.4.1并告诉你
插件缺少测试，前期bug可能多多，还请谅解！！
你存了近百个preset，出bug我心里真是咯噔一下

**Comment by Trantor2098** [comment]
Hi，0.4.1版本已推送，修复了曲线问题；

第二个报错我似乎复现不了，推测是之前的插件漏洞导致你保存的预设文件内容出bug了
可以请你更新到0.4.1，试试还会出现这个bug吗？
如果报错还存在，可以通过重命名预设/重新保存解决嘛？
