### ISSUE TITLE
Error (AttributeError: 'NoneType' object has no attribute 'name')

### ISSUE THREAD

**Issue by xan2622** [Trantor2098/hot_node#6]
Blender version: 4.2.3
Add-on version: 0.7.4

This error appeared in the terminal after doing ??? (in fact, I don't know what I was doing exactly, sorry).
I am trying to reproduce this error but for the moment without  any success. I just wanted to report it anyway, in case it would make sense for you.

```
Traceback (most recent call last):
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\hot_node\props_bl.py", line 145, in _pack_selected_name_update
    old_name = props_py.gl_pack_selected.name
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\hot_node\props_bl.py", line 139, in _pack_selected_name_update

```

**Comment by xan2622** [comment]
No, Hot Node doesn't crash.

**Comment by Trantor2098** [comment]
That's good
